name: Release

on:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.1.2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
            ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/armhf
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update docker hub description
        uses: peter-evans/dockerhub-description@v3.4.2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Sign the published Docker image
        run: |
          IMAGE_TAGS="${{ steps.meta.outputs.tags }}"
          DIGEST="${{ steps.build-and-push.outputs.digest }}"
          for TAG in $IMAGE_TAGS; do
            cosign sign --yes "$TAG@$DIGEST"
          done

      - name: Verify the signature of the published Docker image
        env:
          IDENTITY: "https://github.com/khulnasoft/deployflow/.github/workflows/release.yml@.*"
          OIDC_ISSUER: "https://token.actions.githubusercontent.com"
        run: |
          IMAGE_TAGS="${{ steps.meta.outputs.tags }}"
          DIGEST="${{ steps.build-and-push.outputs.digest }}"
          for TAG in $IMAGE_TAGS; do
            cosign verify "$TAG@$DIGEST" --certificate-identity-regexp=$IDENTITY --certificate-oidc-issuer=$OIDC_ISSUER
          done
